name: 'Terraform'

on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
   
    defaults:
      run:
        shell: bash

    environment:
      name: stage

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1


    - name: Terraform Init
      run: terraform init
      working-directory: ./kubeadm-azure

    - name: Terraform Format
      run: terraform fmt -check
      working-directory: ./kubeadm-azure
      
    - name: Terraform Plan
      run: terraform plan
      working-directory: ./kubeadm-azure
      
    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./kubeadm-azure
