name: 'Terraform'

on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
   
    defaults:
      run:
        shell: bash

    environment:
      name: stage

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Terraform Init
      run: terraform init
      working-directory: ./kubeadm-azure
      
    - name: Terraform Plan
      run: terraform plan -var="azure_subscription_id=${{ secrets.TF_ARM_SUBSCRIPTION_ID}}" -var="azure_client_id=${{ secrets.TF_ARM_CLIENT_ID}}" -var="azure_client_secret=${{ secrets.TF_ARM_CLIENT_SECRET }}" -var="azure_tenant_id=${{ secrets.TF_ARM_TENANT_ID}}"
      working-directory: ./kubeadm-azure
      
    - name: Terraform Apply
      run: terraform apply -var="azure_subscription_id=${{ secrets.TF_ARM_SUBSCRIPTION_ID}}" -var="azure_client_id=${{ secrets.TF_ARM_CLIENT_ID}}" -var="azure_client_secret=${{ secrets.TF_ARM_CLIENT_SECRET }}" -var="azure_tenant_id=${{ secrets.TF_ARM_TENANT_ID}}" -auto-approve
      working-directory: ./kubeadm-azure
